  <form action="processData_form.php" method="POST">
    <label for="name">Nama Lengkap:</label><br>
    <input type="text" id="name" name="name" required>
    <br><br>

    <label for="nim">NIM (Nomor Induk Mahasiswa):</label><br>
    <input type="text" id="nim" name="nim" required>
    <br><br>
        
    <label for="email">Email Aktif:</label><br>
    <input type="email" id="email" name="email" required>
    <br><br>
    <input type="submit" value="Submit">
</form>
        